### ISSUE TITLE
Diagrama corregido

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-8-diagrama-de-clases-equipo-de-melissa#2]
[Diagrama de Clases-1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-diagrama-de-clases-equipo-de-melissa/files/10223691/Diagrama.de.Clases-1.pdf)

**Comment by JudithReynaCS** [comment]
CALIFICACION:50%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
